### ISSUE TITLE
Wrong source location for error

### ISSUE THREAD

**Issue by soegaard** [akeep/nanopass-framework-racket#10]
The following program uses the same variable twice.
The error is correct, but I expected DrRacket to highlight the second e in the definitions window.
# lang nanopass

(define (constant? c)
  (number? c))

(define-language L
  (terminals
   (constant  (c)))
  (Expr (e)
    c
    (if e e)))

**Comment by akeep** [comment]
I think I have a change in that should fix this.  I've tested with Racket 6.2, and when I started Dr. Racket did not provide a "jump to error" button, but after my changes it does (and it is the second occurrence that it jumps to).
