### ISSUE TITLE
Internal error: private/records.rkt:465:43: unique-symbol: contract violation

### ISSUE THREAD

**Issue by soegaard** [akeep/nanopass-framework-racket#17]
# lang nanopass

(define-language Lsrc
  (entry Expr)
  (terminals
   (symbol (x))
   (syntax (s)))

  (Binding (b)
    [(x ...) e])

  (Expr (e)
    x
    (let-values s (b ...) e0 e1 ...)))

Dropbox/GitHub/nanopass-framework-racket/private/records.rkt:465:43: unique-symbol: contract violation
  expected: identifier?
  given: #<syntax:9:5 (x ...)>
  in: an element of
      the rest argument of
      (->*
       (identifier?)
       #:rest
       (listof identifier?)
       symbol?)
  contract from: 
      <pkgs>/nanopass-framework-racket/private/helpers.rkt
  blaming: <pkgs>/nanopass-framework-racket/private/records.rkt
   (assuming the contract is correct)
  at: <pkgs>/nanopass-framework-racket/private/helpers.rkt:34.5

**Comment by akeep** [comment]
fixed by commit 79944d6 by Leif Andersen.
