### ISSUE TITLE
Internal Error (Output nonterminal for pass transformation is unbound)

### ISSUE THREAD

**Issue by soegaard** [akeep/nanopass-framework-racket#19]
In the program below Foo is not bound as a nonterminal.
The program provokes an internal error rather than "Error: Foo is not defined as a nonterminal".
# lang nanopass

(define-language Lsrc
  (entry Expr)
  (terminals
   (symbol (x)))

  (Expr (e)
    x))

(define-pass parse : \* (stx) -> Lsrc ()
  (definitions)

  (foo : \* (E) -> Foo ()
       `,'t)

  (foo stx))

**Comment by LeifAndersen** [comment]
PR21 fixes this issue.
