### ISSUE TITLE
Internal error when language not defined in define-pass

### ISSUE THREAD

**Issue by soegaard** [akeep/nanopass-framework-racket#26]
This program provokes an internal error:
# lang nanopass

(define-pass categorize-applications : L0 (Expr) -> L1 ()
  (definitions)
  (Expr : Expr (E) -> Expr ()))

Dropbox/GitHub/nanopass-framework-racket/private/pass.rkt:1440:33: syntax-local-value: not defined as syntax  identifier: #<syntax:3:39 L0>

A better error would be:

   L0 is not defined as a nanopass language (using define-language)

**Comment by akeep** [comment]
Closed by fix to #12
