### ISSUE TITLE
Please add the racket topic to this repo

### ISSUE THREAD

**Issue by spdegabrielle** [akeep/nanopass-framework-racket#44]
Hi ,
Please add the racket topic to this repo - I think others will be interested and this will help them find it at https://github.com/topics/racket

https://help.github.com/en/articles/classifying-your-repository-with-topics

Kind regards,

Stephen

**Comment by akeep** [comment]
As you noticed (and is noted at the top of the readme) this is no longer the active repository for the Racket version of the nanopass framework.
